name: idoru
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.1.4

  youtube_player_flutter: ^8.1.0

  carousel_slider: ^4.1.1

  image_picker: ^0.8.5+3

  pod_player: ^0.1.0

  youtube_player_iframe: ^3.0.4
  external_app_launcher: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cafe24
      fonts:
        - asset: assets/fonts/Cafe24/Cafe24Ssurround.ttf
          weight: 800
        - asset: assets/fonts/Cafe24/Cafe24SsurroundAir.ttf
          weight: 100
